# Generated by Django 5.0.1 on 2024-01-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagesettings_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesettings',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Image'),
        ),
    ]
